name: Srivani Ticket Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs at 7:30 AM IST

jobs:
  check-srivani:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            xvfb

      - name: Set Up Minimal Node Project
        run: |
          npm init -y
          npm install puppeteer-core

      - name: Run Puppeteer Script
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" node checkSrivani.js

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: srivani-output
          path: srivani.csv

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: srivani-screenshot
          path: final.png
