name: Run Srivani TagUI Script

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM IST
  workflow_dispatch:

jobs:
  run-tagui-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip libgtk-3-0 libnss3 libxss1 libasound2 xvfb

      - name: Clone TagUI from GitHub
        run: |
          git clone https://github.com/kelaberetiv/tagui.git
          chmod +x tagui/src/tagui

      - name: Run TagUI script
        run: |
          ./tagui/src/tagui srivani.tag

      - name: Upload srivani.csv
        uses: actions/upload-artifact@v4
        with:
          name: srivani-results
          path: srivani.csv
