name: Run Srivani TagUI Script

on:
  schedule:
    - cron: '0 2 * * *' # 7:30 AM IST
  workflow_dispatch:

jobs:
  tagui_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TagUI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          curl -L -o tagui.zip https://github.com/kelaberetiv/TagUI/releases/download/v6.50.0/TagUI_Linux.zip
          unzip tagui.zip
          chmod +x tagui/src/tagui

      - name: List files (for debug)
        run: ls -al

      - name: Run TagUI Script
        run: ./tagui/src/tagui srivani.tag

      - name: Upload CSV Result
        uses: actions/upload-artifact@v4
        with:
          name: srivani-results
          path: srivani.csv
