name: Run Srivani TagUI Script

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 7:30 AM IST
  workflow_dispatch:

jobs:
  run-tagui-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip git libgtk-3-0 libnss3 libxss1 libasound2t64 xvfb

      - name: Install PhantomJS from Bitbucket
        run: |
          curl -L -o phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
          tar -xjf phantomjs.tar.bz2
          sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/
          phantomjs --version

      - name: Install CasperJS
        run: |
          git clone https://github.com/casperjs/casperjs.git
          cd casperjs
          sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
          sudo ln -sf `pwd`/bin/casperjs /usr/bin/casperjs

      - name: Clone TagUI
        run: |
          git clone https://github.com/kelaberetiv/tagui.git
          chmod +x tagui/src/tagui

      - name: Run TagUI script with xvfb and OpenSSL fix
        run: |
          export OPENSSL_CONF=/dev/null
          xvfb-run ./tagui/src/tagui srivani.tag

      - name: Show result CSV
        run: |
          echo "--- srivani.csv ---"
          cat srivani.csv || echo "No output found"

      - name: Upload srivani.csv
        uses: actions/upload-artifact@v4
        with:
          name: srivani-results
          path: srivani.csv
