name: Srivani Token Status Checker

on:
  schedule:
    # Runs every day at 00:00 UTC (adjust as needed using crontab.guru)
    # Remember that GitHub Actions schedules are based on UTC.
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  run_tagui_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TagUI
      # You'll need to install TagUI and its dependencies on the runner.
      # The easiest way is to use a pre-built action or a custom setup.
      # Here's a common approach:
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre unzip chromium-browser
        wget https://github.com/kelaberetiv/TagUI/releases/download/v5.11.0/TagUI_Linux.zip
        unzip TagUI_Linux.zip -d /usr/local/share/
        sudo ln -sf /usr/local/share/TagUI/src/tagui /usr/local/bin/tagui
        tagui # This command initializes TagUI and downloads dependencies

    - name: Run TagUI script
      run: |
        cd flows # Navigate to the directory containing your .tag file
        tagui srivani.tag -headless # Run your TagUI script in headless mode
      env:
        # You might need to set DISPLAY for some TagUI operations,
        # though -headless often makes it unnecessary.
        DISPLAY: ':99.0' # Required for GUI applications in some cases

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: srivani-data
        path: srivani.csv # Adjust path if your script writes elsewhere

    - name: Commit and push CSV (optional, if you want to track it in repo)
      # This step is optional. If you just want to download the CSV as an artifact,
      # you can skip this. If you want the CSV to be committed back to your repo,
      # you'll need to configure Git.
      if: success() # Only run if previous steps succeeded
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add srivani.csv # Assuming the CSV is in the flows directory
        git commit -m "Update Srivani data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
