name: Run Srivani TagUI Script

on:
  schedule:
    - cron: '0 2 * * *' # 7:30 AM IST daily
  workflow_dispatch:

jobs:
  tagui_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TagUI (Corrected URL, lowercase)
        run: |
          curl -O https://raw.githubusercontent.com/kelaberetiv/tagui/main/tagui_install.sh
          chmod +x tagui_install.sh
          ./tagui_install.sh

      - name: Run TagUI Script
        run: ~/tagui/src/tagui srivani.tag

      - name: Upload CSV Result
        uses: actions/upload-artifact@v4
        with:
          name: srivani-results
          path: srivani.csv
